// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urgfzozyopaxqsebnxgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZ2Z6b3p5b3BheHFzZWJueGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDE4NzAsImV4cCI6MjA3MjU3Nzg3MH0.kBExe3x8kSkhaqNbEsmGQxKLNn9uGQGDOAbg2IiatIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});